# This file was generated by GoReleaser. DO NOT EDIT.
class Gapp < Formula
  desc "Small utility cli to ease the use of github"
  homepage ""
  version "0.2.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eikc/gapp/releases/download/v0.2.0-rc1/gapp_0.2.0-rc1_Darwin_x86_64.tar.gz"
    sha256 "7dbc0911966448295f5f94684e5f6f7bdbb2543c802c7b70da19fbb1c0505685"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eikc/gapp/releases/download/v0.2.0-rc1/gapp_0.2.0-rc1_Linux_x86_64.tar.gz"
      sha256 "95459bad12e66a8586b333ff5b2d4143cbc77f6bf25314f6b423332345d34c3c"
    end
  end

  def install
    bin.install "gapp"
  end

  test do
    system "gapp version"
  end
end
