# This file was generated by GoReleaser. DO NOT EDIT.
class Gapp < Formula
  desc "Small utility cli to ease the use of github"
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eikc/gapp/releases/download/v0.2.0/gapp_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "969008efa37ed238bee3edeeab08e07fdc9a20baf1d9f12ca4a021b39613f189"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eikc/gapp/releases/download/v0.2.0/gapp_0.2.0_Linux_x86_64.tar.gz"
      sha256 "9b538eeb748238a963aa457b539abb4a9eb86cd040208a8b580ac844eb2fd7eb"
    end
  end

  def install
    bin.install "gapp"
  end

  test do
    system "gapp version"
  end
end
